### ISSUE TITLE
Update Code

### ISSUE THREAD

**Issue by Chewbaka69** [sephizack/sephiogame#35]
Remplacer certaines fonction par une utilisation plus facile et moin bugger des fois:
Replacer:
```
document.referrer.match(/page=(\w+)/)[1] !=
```
et
```
// Toutes les utilisation de 
gup('')
```
par
```
unsafeWindow.currentPage !=
```

Déplacer le bouton en bas plutôt que en haut peut être:
```
document.getElementById('menuTable').innerHTML = '<li style="height:0px;position: relative;top: -31px;"><span class="menu_icon"><div class="menuImage galaxy" style="background:url(http://www.sephiogame.com/script/sephi_script_logo.png);background-position-x:0px;' + bonus_style + '"></div></span><a class="menubutton ' + bonus_class + '" href="https://' + univers + '/game/index.php?page=galaxy&sephiScript=1" target="_self"><span class="textlabel">SephiOGame</span></a></li>' + document.getElementById('menuTable').innerHTML;
```
par
```
document.getElementById('menuTable').innerHTML = document.getElementById('menuTable').innerHTML + '<li style="height:0px;position: relative;top: -31px;"><span class="menu_icon"><div class="menuImage galaxy" style="background:url(http://www.sephiogame.com/script/sephi_script_logo.png);background-position-x:0px;' + bonus_style + '"></div></span><a class="menubutton ' + bonus_class + '" href="https://' + univers + '/game/index.php?page=galaxy&sephiScript=1" target="_self"><span class="textlabel">SephiOGame</span></a></li>';
```

Il faut aussi revoir le drag&drop de la liste de construction, car elle ne fonctionne pas parfaitement.

La liste de construction a une utilisation bizarre car les technologies ne se lance pas dans l'ordre d'ajout, mais quand elles sont possible.

**Comment by Chewbaka69** [comment]
Sur la page galaxy, les planètes sont vérifié par nom, il faut le changer par id

**Comment by sephizack** [comment]
- Pour l'extraction des parametrers des URL je ne vois pas de probleme avec gup. J'ai remplacé document.referrer.match par gup par contre.
- Déplacer le bouton, je ne vois pas pourquoi.
- Pour la liste de construction j'ai fixé quelques bugs (drag&drop, supprimer construction)
Sinon pour les technologies c'est voulu il y a en fait 3 listes en parallèle, batiments, vaisseaux et recherches.

- Pour "Sur la page galaxy, les planètes sont vérifié par nom, il faut le changer par id" je ne vois pas. Sur la page galaxy les frigos sont bien vérifié par ID.

**Comment by Chewbaka69** [comment]
Pour les frigos, javoue que j'ai pas regardé le code mais javais mas planète qui s'appelé planète mère et il y en avait d'autre aussi sur dans mon système solaire et quand sur certaine je n'avais pas l'option ajouter à mes frigos et c'était sur celle ayant le même nom que la mienne.

**Comment by Chewbaka69** [comment]
tu peux fermer

**Comment by bouhouhou** [comment]
Arg, ne fonctionne plus avec la version 7 !
