### ISSUE TITLE
Plus d'update ?

### ISSUE THREAD

**Issue by Shawcs** [sephizack/sephiogame#37]
Salut, le projet est abandonné ? plus d’évolution pour fonctionner avec la nouvelle version d'Ogame ?

dans tous les cas super boulot je me souvient il y a 3 ans quand je m'en servait c’était du tonner !

**Comment by Chewbaka69** [comment]
Bonjour, j'ai repris le projet et je fais quelque maj, si tu as des bugs tu peux venir sur le discord pour nous aider à les fix

**Comment by Shawcs** [comment]
Salut a toi. Oui j'ai vue je suis déjà sur le discord. Pour le coups je ferme la request car en effet ca re fonctionne après ton patch.
